# Generated by Django 5.2.8 on 2026-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=30, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('number', models.IntegerField(verbose_name='تعداد نفرات')),
                ('data', models.DateField(default='2026-01-01', verbose_name='تاریخ ')),
                ('time', models.DateField(verbose_name='زمان')),
            ],
        ),
    ]
