# Generated by Django 5.2.8 on 2026-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='time',
            field=models.DateField(default='08:00:00', verbose_name='زمان'),
        ),
    ]
