# Generated by Django 5.2.8 on 2026-04-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_reservemodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservemodel',
            name='time',
            field=models.TimeField(default='08:00:00', verbose_name='زمان'),
        ),
    ]
