# Generated by Django 5.2.8 on 2026-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(default=100000, verbose_name='قیمت')),
                ('time', models.IntegerField(default=2, verbose_name='زمان انتظار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='نام غذا')),
                ('image', models.ImageField(upload_to='webs/', verbose_name='عکس غذا')),
                ('type', models.CharField(choices=[('iranifood', 'غذای ایرانی'), ('fastfod', 'فست فود'), ('salad', 'سالاد')], default='fast food', max_length=50, verbose_name='نوع غذا')),
            ],
        ),
    ]
