# Generated by Django 5.2.8 on 2026-04-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('iranifood', 'غذای ایرانی'), ('fastfood', 'فست فود'), ('salad', 'سالاد')], default='fast food', max_length=50, verbose_name='نوع غذا'),
        ),
    ]
